### ISSUE TITLE
TypeError: Cannot read property 'Television' of undefined

### ISSUE THREAD

**Issue by pro-sumer** [smockle/homebridge-harmony-tv#47] opened 2020-05-27 20:52 UTC
Homebridge crashes when I add this plugin:

```
May 27 22:46:24 pi-hb homebridge[14520]: [5/27/2020, 10:46:24 PM] [Sony TV] Initializing HarmonyTV accessory...
May 27 22:46:24 pi-hb homebridge[14520]: [5/27/2020, 10:46:24 PM] TypeError: Cannot read property 'Television' of undefined
```

Relevant part of "accessories" from configuration file:
```
  {
    "accessory": "HarmonyTV",
    "name": "Sony TV",
    "host": "192.168.1.214",
    "remoteId": "<REDACTED>"
  }
````

**Node.js version:**
v12.16.3

**Homebridge version:**
1.1.0

**Plugin version:**
5.0.1

**Comment by smockle** [comment] 2020-05-27 21:17
Thanks for reporting this @pro-sumer! This is likely a regression introduced by #46, which I merged prematurely. I’ve published a new version of the plugin [`5.0.4`](https://www.npmjs.com/package/homebridge-harmony-tv-smockle/v/5.0.4)—would you mind updating to that version and checking whether this issue persists?

**Comment by pro-sumer** [comment] 2020-05-27 21:29
Unfortunately it persists with v5.0.4:

```
May 27 23:23:19 pi-hb homebridge[1065]: [5/27/2020, 11:23:19 PM] [Sony TV] Initializing HarmonyTV accessory...
May 27 23:23:19 pi-hb homebridge[1065]: [5/27/2020, 11:23:19 PM] TypeError: Cannot read property 'Television' of undefined
May 27 23:23:19 pi-hb homebridge[1065]:     at new HarmonyTVAccessory (/usr/lib/node_modules/homebridge-harmony-tv-smockle/dis
May 27 23:23:19 pi-hb homebridge[1065]:     at /usr/lib/node_modules/homebridge/src/server.ts:356:50
May 27 23:23:19 pi-hb homebridge[1065]:     at Array.forEach (<anonymous>)
May 27 23:23:19 pi-hb homebridge[1065]:     at Server._loadAccessories (/usr/lib/node_modules/homebridge/src/server.ts:329:29)
May 27 23:23:19 pi-hb homebridge[1065]:     at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:155:12)
May 27 23:23:19 pi-hb homebridge[1065]:     at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
May 27 23:23:19 pi-hb homebridge[1065]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
May 27 23:23:19 pi-hb homebridge[1065]:     at Module._compile (internal/modules/cjs/loader.js:1133:30)
May 27 23:23:19 pi-hb homebridge[1065]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
May 27 23:23:19 pi-hb homebridge[1065]:     at Module.load (internal/modules/cjs/loader.js:977:32)
May 27 23:23:19 pi-hb homebridge[1065]:     at Function.Module._load (internal/modules/cjs/loader.js:877:14)
May 27 23:23:19 pi-hb homebridge[1065]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12
May 27 23:23:19 pi-hb homebridge[1065]:     at internal/main/run_main_module.js:18:47
May 27 23:23:19 pi-hb homebridge[1065]: [5/27/2020, 11:23:19 PM] Got SIGTERM, shutting down Homebridge...
```

(after I modified my config file to have a `deviceId` and `commands`)

**Comment by smockle** [comment] 2020-05-27 21:51
Thanks for the update @pro-sumer. I’ll take a look.

The [release notes](https://github.com/homebridge/homebridge/releases/tag/1.1.0) for homebridge `v1.1.0` mentioned:
> **Plugins Using TypeScript:** Homebridge now only exports types that are safe to use in your code and won't result in the homebridge library being a runtime dependency. If you have been using types correctly then you will not be impacted by this change.

I suspect that is the source of the issue.

**Comment by smockle** [comment] 2020-05-27 21:55
To expand on my comment above, the `yarn.lock` file [specifies homebridge `v1.0.4`](https://github.com/smockle/homebridge-harmony-tv/blob/40db542d68b757485c2cdf9f245f1ca8ba4d8a20/yarn.lock#L363-L365), so that’s the version the plugin has been tested with, but the `yarn.lock` file isn’t included in the [published package](https://unpkg.com/browse/homebridge-harmony-tv-smockle@5.0.4/), and the version range in the `package.json` includes `v1.1.0`.

**Comment by smockle** [comment] 2020-05-28 01:19
I switched to only `import type` from `homebridge` in https://github.com/smockle/homebridge-harmony-tv/commit/a02439137689dff392512fadc39ecbf710dd90de, which was published as version [`5.0.6`](https://www.npmjs.com/package/homebridge-harmony-tv-smockle/v/5.0.6). I ran that version and confirmed I could control my TV.

@pro-sumer, would you mind updating to version `5.0.6` and checking whether the issue is resolved?

**Comment by pro-sumer** [comment] 2020-05-28 08:25
Thanks! The plug-in does start now and I can partially control my (Sony Bravia) TV, but I'm not sure what to expect (I only got my Harmony Hub this week).

This is what I see:
![tv](https://user-images.githubusercontent.com/44335102/83116698-6e265580-a0cc-11ea-9d4b-2fae5ee67871.png)

Switching between Analog/Digital/HDMI1 works, but HDMI4 I can't select, which is a pity, because that's where my Apple TV is connected to.

I was expecting that I would also be able to change channels or volume, but that's not functionality offered by this plug-in?

(I do have commands for all digits, channel down/up, mute, volume down/up in my configuration)

**Comment by smockle** [comment] 2020-05-28 13:33
> Switching between Analog/Digital/HDMI1 works, but HDMI4 I can't select, which is a pity, because that's where my Apple TV is connected to.

That’s surprising—at first glance, I don’t see a reason the input-related code ([harmony-tv-accessory.ts#L41-L44](https://github.com/smockle/homebridge-harmony-tv/blob/9263c96a5a8ac90a85ac7b50807313001fe33f92/src/lib/harmony-tv-accessory.ts#L41-L44) and [harmony-tv-accessory.ts#L202-L259](https://github.com/smockle/homebridge-harmony-tv/blob/9263c96a5a8ac90a85ac7b50807313001fe33f92/src/lib/harmony-tv-accessory.ts#L202-L259)) would omit only HDMI 4.

> I was expecting that I would also be able to change channels or volume…

Changing volume is supported by this plugin, but only in the remote app in Control Center (i.e. not the Home app). When the TV is the active device in the remote app, the physical volume buttons on your iPhone/iPad should control the TV’s volume. Here’s a [related Apple Support article](https://support.apple.com/guide/tv/use-ios-or-ipados-control-center-atvb701cadc1/tvos#atvbe1f2446d).

Changing channel is not supported by this plugin. As [mentioned](https://github.com/smockle/homebridge-harmony-tv#update-2019-09-12) in the README, I do not have plans to add additional functionality (recent updates have been in support of Homebridge 1.0 compatibility), but I would be happy to accept pull requests.

> …that’s not functionality offered by this plug-in?

This plugin is pretty limited, and not actively developed. I’d recommend trying out [`homebridge-harmony`](https://github.com/nicoduj/homebridge-harmony)—it’s more full-featured and is actively maintained.

> I only see the accessory in Apple's Home App, not in third-party Apps like Home+ or Eve. Is that expected?

I’m not sure. I did a bit of research: Home+’s FAQ answers a slightly-different question—[“Why is my Apple TV and HomePod not listed?”](https://hochgatterer.me/home/help/faq/#why-is-my-apple-tv-and-homepod-not-listed). Because they are also AirPlay 2 devices, perhaps televisions, like Apple TVs and HomePods, only show up in Apple’s first-party app.

**Closed** 2020-05-28 13:59 UTC
Labels: bug

**Comment by pro-sumer** [comment] 2020-05-28 14:32
Thank you for your support!

Experimenting with [homebridge-harmony](https://github.com/nicoduj/homebridge-harmony) was already on my todo list, so I'll give that higher priority now.
